/* eslint-disable no-unused-vars */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Daniel Patyk (https://sketchfab.com/SirPytan)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/rome-city-scene-daniel-patyk-dae-b9efdb37f0724b9383b5407c504677d6
Title: Rome City Scene Daniel Patyk DAE
*/

import React, { useRef,useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame,useThree } from "@react-three/fiber";
import {a} from '@react-spring/three';

import islandScene from '../glbfiles/island.glb';

const Island=(props)=> {
    const isLandRef=useRef();
  const { nodes, materials } = useGLTF(islandScene);
  return (
    <a.group ref={isLandRef} {...props} >
      <group position={[-4.441, 0, 99.488]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          
          
          geometry={nodes.Ground_Layer_Cobblestone_0.geometry}
          material={materials.Cobblestone}
        />
        <mesh
          
          
          geometry={nodes.Ground_Layer_Dirt_0.geometry}
          material={materials.Dirt}
        />
        <mesh
          
          
          geometry={nodes.Ground_Layer_sewer_0.geometry}
          material={materials.sewer}
        />
      </group>
      <group
        position={[-501.66, 189.398, -418.699]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <mesh
          
          
          geometry={nodes.Top_Layer_Cobblestone_2_0.geometry}
          material={materials.Cobblestone_2}
        />
        <mesh
          
          
          geometry={nodes.Top_Layer_Fence_Handlebar_0.geometry}
          material={materials.Fence_Handlebar}
        />
        <mesh
          
          
          geometry={nodes.Top_Layer_Fence_0.geometry}
          material={materials.Fence}
        />
        <mesh
          
          
          geometry={nodes.Top_Layer_Cobblestone_0.geometry}
          material={materials.Cobblestone}
        />
        <mesh
          
          
          geometry={nodes.Top_Layer_Concrete_0.geometry}
          material={materials.Concrete}
        />
        <mesh
          
          
          geometry={nodes.Top_Layer_Sewer2_0.geometry}
          material={materials.Sewer2}
        />
        <mesh
          
          
          geometry={nodes.Top_Layer_sewer_0.geometry}
          material={materials.sewer}
        />
      </group>
      <group
        position={[479.571, 189.562, 489.682]}
        rotation={[-Math.PI / 2, 0, 0.806]}
      >
        <mesh
          
          
          geometry={nodes.House_Bottom_Border_0.geometry}
          material={materials.Bottom_Border}
        />
        <mesh
          
          
          geometry={nodes.House_Wall_base_0.geometry}
          material={materials.Wall_base}
        />
        <mesh
          
          
          geometry={nodes.House_Basement_0.geometry}
          material={materials.Basement}
        />
        <mesh
          
          
          geometry={nodes.House_Concrete_stairs_0.geometry}
          material={materials.Concrete_stairs}
        />
        <mesh
          
          
          geometry={nodes.House_BrightStone_0.geometry}
          material={materials.BrightStone}
        />
        <mesh
          
          
          geometry={nodes.House_Roof_0.geometry}
          material={materials.Roof}
        />
        <mesh
          
          
          geometry={nodes.House_Roof_Wood_0.geometry}
          material={materials.Roof_Wood}
        />
        <mesh
          
          
          geometry={nodes.House_Windows_and_Door_0.geometry}
          material={materials.Windows_and_Door}
        />
        <mesh
          
          
          geometry={nodes.House_Yellow_Balcony_and_Entrance_0.geometry}
          material={materials.Yellow_Balcony_and_Entrance}
        />
        <mesh
          
          
          geometry={nodes.House_Marbel_0.geometry}
          material={materials.Marbel}
        />
        <mesh
          
          
          geometry={nodes.House_Fence_0.geometry}
          material={materials.Fence_0}
        />
        <mesh
          
          
          geometry={nodes.House_Textshield_0.geometry}
          material={materials.Textshield}
        />
      </group>
      <group
        position={[238.338, 185.908, -239.855]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 4]}
        scale={[1.098, 1, 1.161]}
      >
        <mesh
          
          
          geometry={nodes["House_2_Cable,_Borders_0"].geometry}
          material={materials.Cable_Borders}
        />
        <mesh
          
          
          geometry={nodes.House_2_Bottom_Wall_0.geometry}
          material={materials.Bottom_Wall}
        />
        <mesh
          
          
          geometry={nodes.House_2_Roof_0.geometry}
          material={materials.Roof_0}
        />
        <mesh
          
          
          geometry={nodes.House_2_Middle_Wall_0.geometry}
          material={materials.Middle_Wall}
        />
        <mesh
          
          
          geometry={nodes.House_2_Top_Wall_0.geometry}
          material={materials.Top_Wall}
        />
        <mesh
          
          
          geometry={
            nodes["House_2_Front_Door,_Top_Door_and_Details_0"].geometry
          }
          material={materials.Front_Door_Top_Door_and_Details}
        />
        <mesh
          
          
          geometry={nodes.House_2_Windows_0.geometry}
          material={materials.Windows}
        />
      </group>
      <group
        position={[-401.325, 269.654, -359.218]}
        rotation={[-Math.PI / 2, 0, -0.76]}
        scale={[1, 0.8, 1]}
      >
        <mesh
          
          
          geometry={nodes.House3_Concrete_0.geometry}
          material={materials.Concrete_0}
        />
        <mesh
          
          
          geometry={nodes.House3_Wall_Bottom_0.geometry}
          material={materials.Wall_Bottom}
        />
        <mesh
          
          
          geometry={nodes.House3_Wall_Middle_0.geometry}
          material={materials.Wall_Middle}
        />
        <mesh
          
          
          geometry={nodes.House3_Wood_0.geometry}
          material={materials.Wood}
        />
        <mesh
          
          
          geometry={nodes.House3_Door_and_Window_0.geometry}
          material={materials.Door_and_Window}
        />
        <mesh
          
          
          geometry={nodes.House3_Wall_Top_0.geometry}
          material={materials.Wall_Top}
        />
        <mesh
          
          
          geometry={nodes.House3_Roofwood_0.geometry}
          material={materials.Roofwood}
        />
        <mesh
          
          
          geometry={nodes.House3_Roof_0.geometry}
          material={materials.Roof_1}
        />
      </group>
      <group
        position={[1.555, 459.811, 0.518]}
        rotation={[-1.532, -0.039, -2.357]}
        scale={2.055}
      >
        <mesh
          
          
          geometry={nodes.Hotelsign_Hotelsign_0.geometry}
          material={materials.Hotelsign}
          position={[720.812, -263.435, -1186.662]}
        />
      </group>
      <group
        position={[-534.296, 164.729, 654.346]}
        rotation={[-0.038, 0, 3.068]}
      >
        <group position={[-1.762, -483.478, -6.8]}>
          <mesh
            
            
            geometry={nodes.Tree_Trunk_0.geometry}
            material={materials.Trunk}
          />
          <mesh
            
            
            geometry={nodes.Tree_Branches_0.geometry}
            material={materials.Branches}
          />
        </group>
      </group>
      <group
        position={[-263.334, 164.729, 1025.857]}
        rotation={[-3.13, -1.501, 0.055]}
        scale={0.683}
      >
        <group position={[-1.762, -483.478, -6.8]}>
          <mesh
            
            
            geometry={nodes.Tree015_Trunk_0.geometry}
            material={materials.Trunk}
          />
          <mesh
            
            
            geometry={nodes.Tree015_Branches_0.geometry}
            material={materials.Branches}
          />
        </group>
      </group>
      <group
        position={[1085.736, 164.729, 1082.291]}
        rotation={[-3.13, -1.501, 0.055]}
        scale={0.683}
      >
        <group position={[-1.762, -483.478, -6.8]}>
          <mesh
            
            
            geometry={nodes.Tree016_Trunk_0.geometry}
            material={materials.Trunk}
          />
          <mesh
            
            
            geometry={nodes.Tree016_Branches_0.geometry}
            material={materials.Branches}
          />
        </group>
      </group>
      <group
        position={[1045.176, 164.729, -50.501]}
        rotation={[3.102, -0.665, 0.005]}
        scale={0.855}
      >
        <group position={[-1.762, -483.478, -6.8]}>
          <mesh
            
            
            geometry={nodes.Tree017_Trunk_0.geometry}
            material={materials.Trunk}
          />
          <mesh
            
            
            geometry={nodes.Tree017_Branches_0.geometry}
            material={materials.Branches}
          />
        </group>
      </group>
      <group
        position={[823.69, 164.729, -679.401]}
        rotation={[3.099, 0.099, 0.004]}
        scale={0.855}
      >
        <group position={[-1.762, -483.478, -6.8]}>
          <mesh
            
            
            geometry={nodes.Tree018_Trunk_0.geometry}
            material={materials.Trunk}
          />
          <mesh
            
            
            geometry={nodes.Tree018_Branches_0.geometry}
            material={materials.Branches}
          />
        </group>
      </group>
      <group
        position={[369.358, 447.232, -985.489]}
        rotation={[3.102, -0.676, 0.005]}
        scale={0.855}
      >
        <group position={[-1.762, -483.478, -6.8]}>
          <mesh
            
            
            geometry={nodes.Tree019_Trunk_0.geometry}
            material={materials.Trunk}
          />
          <mesh
            
            
            geometry={nodes.Tree019_Branches_0.geometry}
            material={materials.Branches}
          />
        </group>
      </group>
      <group
        position={[66.767, 447.232, -762.07]}
        rotation={[-0.054, -1.244, 3.13]}
        scale={0.525}
      >
        <group position={[-1.762, -483.478, -6.8]}>
          <mesh
            
            
            geometry={nodes.Tree020_Trunk_0.geometry}
            material={materials.Trunk}
          />
          <mesh
            
            
            geometry={nodes.Tree020_Branches_0.geometry}
            material={materials.Branches}
          />
        </group>
      </group>
      <group
        position={[-118.494, 464.284, -992.725]}
        rotation={[-0.048, -0.913, 3.135]}
        scale={0.631}
      >
        <group position={[-1.762, -483.478, -6.8]}>
          <mesh
            
            
            geometry={nodes.Tree021_Trunk_0.geometry}
            material={materials.Trunk}
          />
          <mesh
            
            
            geometry={nodes.Tree021_Branches_0.geometry}
            material={materials.Branches}
          />
        </group>
      </group>
      <group
        position={[-1084.953, 464.284, -992.725]}
        rotation={[-0.043, 0.012, 3.138]}
        scale={0.631}
      >
        <group position={[-1.762, -483.478, -6.8]}>
          <mesh
            
            
            geometry={nodes.Tree022_Trunk_0.geometry}
            material={materials.Trunk}
          />
          <mesh
            
            
            geometry={nodes.Tree022_Branches_0.geometry}
            material={materials.Branches}
          />
        </group>
      </group>
      <group
        position={[86.155, 403.885, 81.88]}
        rotation={[-Math.PI / 2, 0, -2.356]}
      >
        <mesh
          
          
          geometry={nodes["Streetlatern_Material_#19_0"].geometry}
          material={materials.Material_19_0}
          position={[57.322, 0, 14.959]}
        />
      </group>
      <group
        position={[-84.962, 403.885, -89.237]}
        rotation={[-Math.PI / 2, 0, -2.356]}
      >
        <mesh
          
          
          geometry={nodes["Streetlatern001_Material_#19_0"].geometry}
          material={materials.Material_19_0}
          position={[57.322, 0, 14.959]}
        />
      </group>
      <group
        position={[172.374, 477.103, 818.574]}
        rotation={[-Math.PI / 2, 0, -2.356]}
      >
        <mesh
          
          
          geometry={nodes["Streetlatern002_Material_#19_0"].geometry}
          material={materials.Material_19_0}
          position={[57.322, 0, 14.959]}
        />
      </group>
      <group
        position={[-5.463, 477.103, 640.736]}
        rotation={[-Math.PI / 2, 0, -2.356]}
      >
        <mesh
          
          
          geometry={nodes["Streetlatern003_Material_#19_0"].geometry}
          material={materials.Material_19_0}
          position={[57.322, 0, 14.959]}
        />
      </group>
      <group
        position={[844.788, 488.479, 852.532]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 4]}
      >
        <mesh
          
          
          geometry={nodes["Streetlatern004_Material_#19_0"].geometry}
          material={materials.Material_19_0}
          position={[57.322, 0, 14.959]}
        />
      </group>
      <group
        position={[1035.9, 266.38, 588.234]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 4]}
      >
        <mesh
          
          
          geometry={nodes["Streetlatern005_Material_#19_0"].geometry}
          material={materials.Material_19_0}
          position={[57.322, 0, 14.959]}
        />
      </group>
      <group
        position={[817.568, 407.523, 257.8]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
      >
        <mesh
          
          
          geometry={nodes["Streetlatern006_Material_#19_0"].geometry}
          material={materials.Material_19_0}
          position={[57.322, 0, 14.959]}
        />
      </group>
      <group
        position={[584.638, 407.523, 24.87]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
      >
        <mesh
          
          
          geometry={nodes["Streetlatern007_Material_#19_0"].geometry}
          material={materials.Material_19_0}
          position={[57.322, 0, 14.959]}
        />
      </group>
      <group
        position={[478.815, 407.523, -473.737]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
      >
        <mesh
          
          
          geometry={nodes["Streetlatern008_Material_#19_0"].geometry}
          material={materials.Material_19_0}
          position={[57.322, 0, 14.959]}
        />
      </group>
      <group
        position={[-440.348, 403.885, 115.676]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 4]}
      >
        <mesh
          
          
          geometry={nodes["Streetlatern009_Material_#19_0"].geometry}
          material={materials.Material_19_0}
          position={[57.322, 0, 14.959]}
        />
      </group>
      <group
        position={[-835.025, 403.885, 323.37]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 3]}
      >
        <mesh
          
          
          geometry={nodes["Streetlatern010_Material_#19_0"].geometry}
          material={materials.Material_19_0}
          position={[57.322, 0, 14.959]}
        />
      </group>
      <group
        position={[-486.367, 673.37, 114.611]}
        rotation={[-Math.PI / 2, 0, -2.269]}
      >
        <mesh
          
          
          geometry={nodes["Streetlatern011_Material_#19_0"].geometry}
          material={materials.Material_19_0}
          position={[57.322, 0, 14.959]}
        />
      </group>
      <group
        position={[-867.835, 673.37, -248.256]}
        rotation={[-Math.PI / 2, 0, -2.269]}
      >
        <mesh
          
          
          geometry={nodes["Streetlatern012_Material_#19_0"].geometry}
          material={materials.Material_19_0}
          position={[57.322, 0, 14.959]}
        />
      </group>
      <group
        position={[-479.126, 673.37, -715.11]}
        rotation={[-Math.PI / 2, 0, 2.356]}
      >
        <mesh
          
          
          geometry={nodes["Streetlatern013_Material_#19_0"].geometry}
          material={materials.Material_19_0}
          position={[57.322, 0, 14.959]}
        />
      </group>
      <group
        position={[-142.562, 673.37, -667.738]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
      >
        <mesh
          
          
          geometry={nodes["Streetlatern014_Material_#19_0"].geometry}
          material={materials.Material_19_0}
          position={[57.322, 0, 14.959]}
        />
      </group>
      <mesh
        
        
        geometry={nodes["Streetbench_Material_#38_0"].geometry}
        material={materials.Material_38}
        position={[-584.204, 218.688, 262.646]}
        rotation={[-Math.PI / 2, 0, -1.096]}
      />
      <mesh
        
        
        geometry={nodes["Streetbench001_Material_#38_0"].geometry}
        material={materials.Material_38}
        position={[-754.913, 218.688, 399.934]}
        rotation={[-Math.PI / 2, 0, -0.628]}
      />
      <mesh
        
        
        geometry={nodes["Streetbench002_Material_#38_0"].geometry}
        material={materials.Material_38}
        position={[-816.995, 218.688, 641.422]}
        rotation={[-Math.PI / 2, 0, -0.029]}
      />
      <mesh
        
        
        geometry={nodes["Streetbench003_Material_#38_0"].geometry}
        material={materials.Material_38}
        position={[-395.6, 218.688, 844.877]}
        rotation={[-Math.PI / 2, 0, -0.665]}
      />
      <mesh
        
        
        geometry={nodes["Streetbench004_Material_#38_0"].geometry}
        material={materials.Material_38}
        position={[-427.006, 218.688, 1056.246]}
        rotation={[-Math.PI / 2, 0, 0.254]}
      />
      <mesh
        
        
        geometry={nodes["Streetbench005_Material_#38_0"].geometry}
        material={materials.Material_38}
        position={[690.367, 218.688, -124.595]}
        rotation={[-Math.PI / 2, 0, -0.159]}
      />
      <mesh
        
        
        geometry={nodes["Streetbench006_Material_#38_0"].geometry}
        material={materials.Material_38}
        position={[752.052, 218.688, 79.998]}
        rotation={[-Math.PI / 2, 0, 0.76]}
      />
      <mesh
        
        
        geometry={nodes["Streetbench007_Material_#38_0"].geometry}
        material={materials.Material_38}
        position={[-18.233, 507.124, -892.214]}
        rotation={[-Math.PI / 2, 0, 0.774]}
      />
      <mesh
        
        
        geometry={nodes["Streetbench008_Material_#38_0"].geometry}
        material={materials.Material_38}
        position={[215.441, 507.124, -879.261]}
        rotation={[-Math.PI / 2, 0, 2.299]}
      />
      <mesh
        
        
        geometry={nodes["Streetbench009_Material_#38_0"].geometry}
        material={materials.Material_38}
        position={[105.191, 507.124, -1102.473]}
        rotation={[-Math.PI / 2, 0, 1.625]}
      />
      <mesh
        
        
        geometry={nodes["Streetbench010_Material_#38_0"].geometry}
        material={materials.Material_38}
        position={[518.53, 218.688, -760.939]}
        rotation={[-Math.PI / 2, 0, -0.679]}
      />
      <mesh
        
        
        geometry={nodes["Streetbench011_Material_#38_0"].geometry}
        material={materials.Material_38}
        position={[553.926, 218.688, -539.779]}
        rotation={[-Math.PI / 2, 0, 0.794]}
      />
      <mesh
        
        
        geometry={nodes["Streetbench012_Material_#38_0"].geometry}
        material={materials.Material_38}
        position={[-1063.292, 507.124, -1102.473]}
        rotation={[-Math.PI / 2, 0, 1.581]}
      />
      <mesh
        
        
        geometry={nodes["Streetbench013_Material_#38_0"].geometry}
        material={materials.Material_38}
        position={[-636.895, 507.124, 29.309]}
        rotation={[-Math.PI / 2, 0, -2.346]}
      />
      <mesh
        
        
        geometry={nodes["Trashbin_Material_#19_0"].geometry}
        material={materials.Material_19}
        position={[-812.245, 189.566, 833.416]}
        rotation={[-Math.PI / 2, 0, 3.054]}
      />
      <mesh
        
        
        geometry={nodes["Trashbin001_Material_#19_0"].geometry}
        material={materials.Material_19}
        position={[-272.464, 189.566, 752.606]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        
        
        geometry={nodes["Trashbin002_Material_#19_0"].geometry}
        material={materials.Material_19}
        position={[-167.732, 189.566, -110.232]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        
        
        geometry={nodes["Trashbin003_Material_#19_0"].geometry}
        material={materials.Material_19}
        position={[861.682, 189.566, 214.623]}
        rotation={[-Math.PI / 2, 0, Math.PI / 6]}
      />
      <mesh
        
        
        geometry={nodes["Trashbin004_Material_#19_0"].geometry}
        material={materials.Material_19}
        position={[603.097, 189.566, -890.168]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 4]}
      />
      <mesh
        
        
        geometry={nodes["Trashbin005_Material_#19_0"].geometry}
        material={materials.Material_19}
        position={[123.376, 478.258, -748.438]}
        rotation={[-Math.PI / 2, 0, -1.309]}
      />
      <mesh
        
        
        geometry={nodes["Trashbin006_Material_#19_0"].geometry}
        material={materials.Material_19}
        position={[-1205.927, 478.258, -1090.992]}
        rotation={[-Math.PI / 2, 0, 2.967]}
      />
      <mesh
        
        
        geometry={nodes["Trashbin007_Material_#19_0"].geometry}
        material={materials.Material_19}
        position={[-924.277, 478.258, -276.009]}
        rotation={[-Math.PI / 2, 0, 2.967]}
      />
      <mesh
        
        
        geometry={nodes["Streetpillar_Material_#0_0"].geometry}
        material={materials.Material_0}
        position={[-938.918, 188.198, 1085.196]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.319}
      />
      <mesh
        
        
        geometry={nodes["Streetpillar001_Material_#0_0"].geometry}
        material={materials.Material_0}
        position={[-1043.099, 188.198, 1085.196]}
        rotation={[-Math.PI / 2, 0, -1.222]}
        scale={1.319}
      />
      <mesh
        
        
        geometry={nodes["Streetpillar002_Material_#0_0"].geometry}
        material={materials.Material_0}
        position={[-938.918, 479.756, 298.431]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.319}
      />
      <mesh
        
        
        geometry={nodes["Streetpillar003_Material_#0_0"].geometry}
        material={materials.Material_0}
        position={[-1043.099, 479.756, 298.431]}
        rotation={[-Math.PI / 2, 0, -0.873]}
        scale={1.319}
      />
      <mesh
        
        
        geometry={nodes["Streetpillar004_Material_#0_0"].geometry}
        material={materials.Material_0}
        position={[-1215.167, 478.758, 330.497]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.319}
      />
      <mesh
        
        
        geometry={nodes["Streetpillar005_Material_#0_0"].geometry}
        material={materials.Material_0}
        position={[-1164.327, 478.758, 330.497]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.319}
      />
      <mesh
        
        
        geometry={nodes["Streetpillar006_Material_#0_0"].geometry}
        material={materials.Material_0}
        position={[-1215.167, 478.758, 216.857]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.319}
      />
      <mesh
        
        
        geometry={nodes["Streetpillar007_Material_#0_0"].geometry}
        material={materials.Material_0}
        position={[-1215.167, 478.758, 100.621]}
        rotation={[-Math.PI / 2, 0, -1.309]}
        scale={1.319}
      />
      <mesh
        
        
        geometry={nodes["Streetpillar008_Material_#0_0"].geometry}
        material={materials.Material_0}
        position={[-1215.167, 478.758, -13.019]}
        rotation={[-Math.PI / 2, 0, 0.611]}
        scale={1.319}
      />
      <mesh
        
        
        geometry={nodes["Streetpillar009_Material_#0_0"].geometry}
        material={materials.Material_0}
        position={[-1215.167, 478.758, -125.479]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.319}
      />
      <mesh
        
        
        geometry={nodes["Streetpillar010_Material_#0_0"].geometry}
        material={materials.Material_0}
        position={[-1215.167, 478.758, -239.119]}
        rotation={[-Math.PI / 2, 0, Math.PI / 6]}
        scale={1.319}
      />
      <mesh
        
        
        geometry={nodes["Streetpillar011_Material_#0_0"].geometry}
        material={materials.Material_0}
        position={[-1215.167, 478.758, -355.355]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.319}
      />
      <mesh
        
        
        geometry={nodes["Streetpillar012_Material_#0_0"].geometry}
        material={materials.Material_0}
        position={[-1215.167, 478.758, -468.995]}
        rotation={[-Math.PI / 2, 0, Math.PI / 6]}
        scale={1.319}
      />
      <mesh
        
        
        geometry={nodes["Streetpillar013_Material_#0_0"].geometry}
        material={materials.Material_0}
        position={[-1215.167, 478.758, -588.754]}
        rotation={[-Math.PI / 2, 0, -0.436]}
        scale={1.319}
      />
      <mesh
        
        
        geometry={nodes["Streetpillar014_Material_#0_0"].geometry}
        material={materials.Material_0}
        position={[-1215.167, 478.758, -702.394]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.319}
      />
      <mesh
        
        
        geometry={nodes["Streetpillar015_Material_#0_0"].geometry}
        material={materials.Material_0}
        position={[-1215.167, 478.758, -818.63]}
        rotation={[-Math.PI / 2, 0, 0.436]}
        scale={1.319}
      />
      <mesh
        
        
        geometry={nodes["Streetpillar016_Material_#0_0"].geometry}
        material={materials.Material_0}
        position={[-1215.167, 478.758, -932.27]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.319}
      />
      <mesh
        
        
        geometry={nodes["Bike_Material_#38_0"].geometry}
        material={materials.Material_38_0}
        position={[-103.393, 261.257, 514.533]}
        rotation={[-1.705, 0.112, -0.778]}
        scale={[1.44, 1.08, 1.44]}
      />
      <mesh
        
        
        geometry={nodes["Bike040_Material_#38_0"].geometry}
        material={materials.Material_38_0}
        position={[-1096.09, 551.853, -619.676]}
        rotation={[-Math.PI / 2, 0, -0.739]}
        scale={[1.44, 1.08, 1.44]}
      />
      <mesh
        
        
        geometry={nodes["Bike041_Material_#38_0"].geometry}
        material={materials.Material_38_0}
        position={[-1067.4, 551.853, -651.175]}
        rotation={[-Math.PI / 2, 0, -0.739]}
        scale={[1.44, 1.08, 1.44]}
      />
      <mesh
        
        
        geometry={nodes["Bike042_Material_#38_0"].geometry}
        material={materials.Material_38_0}
        position={[-1039.02, 551.853, -682.334]}
        rotation={[-Math.PI / 2, 0, -0.739]}
        scale={[1.44, 1.08, 1.44]}
      />
      <mesh
        
        
        geometry={nodes["Bike043_Material_#38_0"].geometry}
        material={materials.Material_38_0}
        position={[-1009.769, 551.853, -714.449]}
        rotation={[-Math.PI / 2, 0, -0.739]}
        scale={[1.44, 1.08, 1.44]}
      />
      <mesh
        
        
        geometry={nodes["Bike044_Material_#38_0"].geometry}
        material={materials.Material_38_0}
        position={[-981.079, 551.853, -745.949]}
        rotation={[-Math.PI / 2, 0, -0.739]}
        scale={[1.44, 1.08, 1.44]}
      />
      <mesh
        
        
        geometry={nodes["Bike045_Material_#38_0"].geometry}
        material={materials.Material_38_0}
        position={[-952.699, 551.853, -777.107]}
        rotation={[-Math.PI / 2, 0, -0.739]}
        scale={[1.44, 1.08, 1.44]}
      />
      <mesh
        
        
        geometry={nodes["Bike046_Material_#38_0"].geometry}
        material={materials.Material_38_0}
        position={[-922.548, 551.853, -810.21]}
        rotation={[-Math.PI / 2, 0, -0.739]}
        scale={[1.44, 1.08, 1.44]}
      />
      <mesh
        
        
        geometry={nodes["Bike047_Material_#38_0"].geometry}
        material={materials.Material_38_0}
        position={[-893.858, 551.853, -841.71]}
        rotation={[-Math.PI / 2, 0, -0.739]}
        scale={[1.44, 1.08, 1.44]}
      />
      <mesh
        
        
        geometry={nodes["Bike048_Material_#38_0"].geometry}
        material={materials.Material_38_0}
        position={[-865.478, 551.853, -872.868]}
        rotation={[-Math.PI / 2, 0, -0.739]}
        scale={[1.44, 1.08, 1.44]}
      />
      <mesh
        
        
        geometry={nodes["Bike049_Material_#38_0"].geometry}
        material={materials.Material_38_0}
        position={[-836.227, 551.853, -904.984]}
        rotation={[-Math.PI / 2, 0, -0.739]}
        scale={[1.44, 1.08, 1.44]}
      />
      <mesh
        
        
        geometry={nodes["Bike050_Material_#38_0"].geometry}
        material={materials.Material_38_0}
        position={[-807.537, 551.853, -936.483]}
        rotation={[-Math.PI / 2, 0, -0.739]}
        scale={[1.44, 1.08, 1.44]}
      />
      <mesh
        
        
        geometry={nodes["Bike051_Material_#38_0"].geometry}
        material={materials.Material_38_0}
        position={[-779.157, 551.853, -967.642]}
        rotation={[-Math.PI / 2, 0, -0.739]}
        scale={[1.44, 1.08, 1.44]}
      />
      <mesh
        
        
        geometry={nodes["Streetpillar017_Material_#0_0"].geometry}
        material={materials.Material_0}
        position={[-1075.227, 478.758, -593.821]}
        rotation={[-Math.PI / 2, 0, 0.873]}
        scale={[1.076, 1.076, 1.246]}
      />
      <mesh
        
        
        geometry={nodes["Streetpillar018_Material_#0_0"].geometry}
        material={materials.Material_0}
        position={[-1048.394, 478.758, -625.799]}
        rotation={[-Math.PI / 2, 0, 0.873]}
        scale={[1.076, 1.076, 1.246]}
      />
      <mesh
        
        
        geometry={nodes["Streetpillar019_Material_#0_0"].geometry}
        material={materials.Material_0}
        position={[-1020.627, 478.758, -658.89]}
        rotation={[-Math.PI / 2, 0, 0.873]}
        scale={[1.076, 1.076, 1.246]}
      />
      <mesh
        
        
        geometry={nodes["Streetpillar020_Material_#0_0"].geometry}
        material={materials.Material_0}
        position={[-992.67, 478.758, -692.208]}
        rotation={[-Math.PI / 2, 0, 0.794]}
        scale={[1.076, 1.076, 1.246]}
      />
      <mesh
        
        
        geometry={nodes["Streetpillar021_Material_#0_0"].geometry}
        material={materials.Material_0}
        position={[-962.677, 478.758, -722.726]}
        rotation={[-Math.PI / 2, 0, 0.794]}
        scale={[1.076, 1.076, 1.246]}
      />
      <mesh
        
        
        geometry={nodes["Streetpillar022_Material_#0_0"].geometry}
        material={materials.Material_0}
        position={[-933.793, 478.758, -752.894]}
        rotation={[-Math.PI / 2, 0, 0.794]}
        scale={[1.076, 1.076, 1.246]}
      />
      <mesh
        
        
        geometry={nodes["Streetpillar023_Material_#0_0"].geometry}
        material={materials.Material_0}
        position={[-902.658, 478.758, -785.341]}
        rotation={[-Math.PI / 2, 0, 0.794]}
        scale={[1.076, 1.076, 1.246]}
      />
      <mesh
        
        
        geometry={nodes["Streetpillar024_Material_#0_0"].geometry}
        material={materials.Material_0}
        position={[-873.469, 478.758, -815.816]}
        rotation={[-Math.PI / 2, 0, 0.794]}
        scale={[1.076, 1.076, 1.246]}
      />
      <mesh
        
        
        geometry={nodes["Streetpillar025_Material_#0_0"].geometry}
        material={materials.Material_0}
        position={[-844.94, 478.758, -847.254]}
        rotation={[-Math.PI / 2, 0, 0.794]}
        scale={[1.076, 1.076, 1.246]}
      />
      <mesh
        
        
        geometry={nodes["Streetpillar026_Material_#0_0"].geometry}
        material={materials.Material_0}
        position={[-816.227, 478.758, -880.046]}
        rotation={[-Math.PI / 2, 0, 0.794]}
        scale={[1.076, 1.076, 1.246]}
      />
      <mesh
        
        
        geometry={nodes["Streetpillar027_Material_#0_0"].geometry}
        material={materials.Material_0}
        position={[-787.652, 478.758, -911.523]}
        rotation={[-Math.PI / 2, 0, 0.794]}
        scale={[1.076, 1.076, 1.246]}
      />
      <mesh
        
        
        geometry={nodes["Streetpillar028_Material_#0_0"].geometry}
        material={materials.Material_0}
        position={[-760.499, 478.758, -943.693]}
        rotation={[-Math.PI / 2, 0, 0.794]}
        scale={[1.076, 1.076, 1.246]}
      />
      <mesh
        
        
        geometry={nodes["Bike052_Material_#38_0"].geometry}
        material={materials.Material_38_0}
        position={[-865.107, 551.853, -435.177]}
        rotation={[-Math.PI / 2, 0, -0.739]}
        scale={[1.44, 1.08, 1.44]}
      />
      <mesh
        
        
        geometry={nodes["Bike053_Material_#38_0"].geometry}
        material={materials.Material_38_0}
        position={[-836.417, 551.853, -466.676]}
        rotation={[-Math.PI / 2, 0, -0.739]}
        scale={[1.44, 1.08, 1.44]}
      />
      <mesh
        
        
        geometry={nodes["Bike054_Material_#38_0"].geometry}
        material={materials.Material_38_0}
        position={[-808.037, 551.853, -497.834]}
        rotation={[-Math.PI / 2, 0, -0.739]}
        scale={[1.44, 1.08, 1.44]}
      />
      <mesh
        // 
        // 
        geometry={nodes["Bike055_Material_#38_0"].geometry}
        material={materials.Material_38_0}
        position={[-778.786, 551.853, -529.95]}
        rotation={[-Math.PI / 2, 0, -0.739]}
        scale={[1.44, 1.08, 1.44]}
      />
      <mesh
        // 
        // 
        geometry={nodes["Bike056_Material_#38_0"].geometry}
        material={materials.Material_38_0}
        position={[-750.095, 551.853, -561.45]}
        rotation={[-Math.PI / 2, 0, -0.739]}
        scale={[1.44, 1.08, 1.44]}
      />
      <mesh
        // 
        // 
        geometry={nodes["Bike057_Material_#38_0"].geometry}
        material={materials.Material_38_0}
        position={[-721.716, 551.853, -592.608]}
        rotation={[-Math.PI / 2, 0, -0.739]}
        scale={[1.44, 1.08, 1.44]}
      />
      <mesh
        // 
        // 
        geometry={nodes["Bike058_Material_#38_0"].geometry}
        material={materials.Material_38_0}
        position={[-691.565, 551.853, -625.711]}
        rotation={[-Math.PI / 2, 0, -0.739]}
        scale={[1.44, 1.08, 1.44]}
      />
      <mesh
        // 
        // 
        geometry={nodes["Bike059_Material_#38_0"].geometry}
        material={materials.Material_38_0}
        position={[-662.875, 551.853, -657.211]}
        rotation={[-Math.PI / 2, 0, -0.739]}
        scale={[1.44, 1.08, 1.44]}
      />
      <mesh
        // 
        // 
        geometry={nodes["Bike060_Material_#38_0"].geometry}
        material={materials.Material_38_0}
        position={[-634.495, 551.853, -688.369]}
        rotation={[-Math.PI / 2, 0, -0.739]}
        scale={[1.44, 1.08, 1.44]}
      />
      <mesh
        // 
        // 
        geometry={nodes["Bike061_Material_#38_0"].geometry}
        material={materials.Material_38_0}
        position={[-605.244, 551.853, -720.485]}
        rotation={[-Math.PI / 2, 0, -0.739]}
        scale={[1.44, 1.08, 1.44]}
      />
      <mesh
        // 
        // 
        geometry={nodes["Bike062_Material_#38_0"].geometry}
        material={materials.Material_38_0}
        position={[-576.553, 551.853, -751.984]}
        rotation={[-Math.PI / 2, 0, -0.739]}
        scale={[1.44, 1.08, 1.44]}
      />
      <mesh
        // 
        // 
        geometry={nodes["Bike063_Material_#38_0"].geometry}
        material={materials.Material_38_0}
        position={[-548.174, 551.853, -783.142]}
        rotation={[-Math.PI / 2, 0, -0.739]}
        scale={[1.44, 1.08, 1.44]}
      />
      <mesh
        // 
        // 
        geometry={nodes["Streetpillar029_Material_#0_0"].geometry}
        material={materials.Material_0}
        position={[-844.243, 478.758, -409.322]}
        rotation={[-Math.PI / 2, 0, 0.873]}
        scale={[1.076, 1.076, 1.246]}
      />
      <mesh
        // 
        // 
        geometry={nodes["Streetpillar030_Material_#0_0"].geometry}
        material={materials.Material_0}
        position={[-817.411, 478.758, -441.3]}
        rotation={[-Math.PI / 2, 0, 0.873]}
        scale={[1.076, 1.076, 1.246]}
      />
      <mesh
        // 
        // 
        geometry={nodes["Streetpillar031_Material_#0_0"].geometry}
        material={materials.Material_0}
        position={[-789.644, 478.758, -474.391]}
        rotation={[-Math.PI / 2, 0, 0.873]}
        scale={[1.076, 1.076, 1.246]}
      />
      <mesh
        // 
        // 
        geometry={nodes["Streetpillar032_Material_#0_0"].geometry}
        material={materials.Material_0}
        position={[-761.687, 478.758, -507.709]}
        rotation={[-Math.PI / 2, 0, 0.794]}
        scale={[1.076, 1.076, 1.246]}
      />
      <mesh
        // 
        // 
        geometry={nodes["Streetpillar033_Material_#0_0"].geometry}
        material={materials.Material_0}
        position={[-731.694, 478.758, -538.227]}
        rotation={[-Math.PI / 2, 0, 0.794]}
        scale={[1.076, 1.076, 1.246]}
      />
      <mesh
        // 
        // 
        geometry={nodes["Streetpillar034_Material_#0_0"].geometry}
        material={materials.Material_0}
        position={[-702.809, 478.758, -568.395]}
        rotation={[-Math.PI / 2, 0, 0.794]}
        scale={[1.076, 1.076, 1.246]}
      />
      <mesh
        // 
        // 
        geometry={nodes["Streetpillar035_Material_#0_0"].geometry}
        material={materials.Material_0}
        position={[-671.674, 478.758, -600.842]}
        rotation={[-Math.PI / 2, 0, 0.794]}
        scale={[1.076, 1.076, 1.246]}
      />
      <mesh
        // 
        // 
        geometry={nodes["Streetpillar036_Material_#0_0"].geometry}
        material={materials.Material_0}
        position={[-642.486, 478.758, -631.317]}
        rotation={[-Math.PI / 2, 0, 0.794]}
        scale={[1.076, 1.076, 1.246]}
      />
      <mesh
        // 
        // 
        geometry={nodes["Streetpillar037_Material_#0_0"].geometry}
        material={materials.Material_0}
        position={[-613.957, 478.758, -662.754]}
        rotation={[-Math.PI / 2, 0, 0.794]}
        scale={[1.076, 1.076, 1.246]}
      />
      <mesh
        // 
        // 
        geometry={nodes["Streetpillar038_Material_#0_0"].geometry}
        material={materials.Material_0}
        position={[-585.244, 478.758, -695.547]}
        rotation={[-Math.PI / 2, 0, 0.794]}
        scale={[1.076, 1.076, 1.246]}
      />
      <mesh
        // 
        // 
        geometry={nodes["Streetpillar039_Material_#0_0"].geometry}
        material={materials.Material_0}
        position={[-556.669, 478.758, -727.023]}
        rotation={[-Math.PI / 2, 0, 0.794]}
        scale={[1.076, 1.076, 1.246]}
      />
      <mesh
        // 
        // 
        geometry={nodes["Streetpillar040_Material_#0_0"].geometry}
        material={materials.Material_0}
        position={[-529.516, 478.758, -759.193]}
        rotation={[-Math.PI / 2, 0, 0.794]}
        scale={[1.076, 1.076, 1.246]}
      />
    </a.group>
  );
}

// useGLTF.preload("/rome_city_scene_daniel_patyk_dae.glb");

export default Island;